version: '3'
services:
    web:
        image: specmore/spectacular-web:latest
        ports:
            - "80:80"
        depends_on: 
            - backend
        environment:
            - API_LOCATION=http://backend
    backend:
        image: specmore/spectacular-backend:latest
        environment: 
            - GITHUB_APP_ID=${SPECTACULAR_GITHUB_APP_ID:?SPECTACULAR_GITHUB_APP_ID needs to be set in a .env file with a GitHub app id}
            - GITHUB_APP_PRIVATE_KEY_FILE_PATH=/usr/spectacular/github.private-key.pem
            - GITHUB_API_ROOT_URL=${SPECTACULAR_GITHUB_API_ROOT_URL:-https://api.github.com}
            - JWT_SHARED_SECRET=${SPECTACULAR_JWT_SHARED_SECRET:?SPECTACULAR_JWT_SHARED_SECRET needs to be set in a .env file with a 32byte text secret}   
            - GITHUB_CLIENT_ID=${SPECTACULAR_GITHUB_CLIENT_ID:?SPECTACULAR_GITHUB_CLIENT_ID needs to be set in a .env file with a GitHub app client id}
            - GITHUB_CLIENT_SECRET=${SPECTACULAR_GITHUB_CLIENT_SECRET:?SPECTACULAR_GITHUB_CLIENT_SECRET needs to be set in a .env file with a GitHub app client secret}
        volumes:
            - ${SPECTACULAR_GITHUB_APP_PRIVATE_KEY_FILE_PATH:?SPECTACULAR_GITHUB_APP_PRIVATE_KEY_FILE_PATH needs to be set in a .env file with the location of a .pem private key provided for the GitHub app}:/usr/spectacular/github.private-key.pem:ro
