version: '3'
services:
    web:
        build: 
            context: .
            dockerfile: ./docker/Dockerfile-web
        ports:
        - "80:80"
        depends_on: 
            - backend
            - auth
        environment:
            - API_LOCATION=http://backend
            - AUTH_LOCATION=http://auth:8080
            - GITHUB_APP_INSTALLATION_ID=${SPECTACULAR_GITHUB_APP_INSTALLATION_ID:?SPECTACULAR_GITHUB_APP_INSTALLATION_ID needs to be set in a .env file with a GitHub app installation id}
    backend:
        build: 
            context: .
            dockerfile: ./docker/Dockerfile-backend
        environment: 
            - GITHUB_APP_ID=${SPECTACULAR_GITHUB_APP_ID:?SPECTACULAR_GITHUB_APP_ID needs to be set in a .env file with a GitHub app id}
            - GITHUB_APP_PRIVATE_KEY_FILE_PATH=/usr/spectacular/github.private-key.pem
            - GITHUB_API_ROOT_URL=${SPECTACULAR_GITHUB_API_ROOT_URL:-https://api.github.com}
            - JWT_SHARED_SECRET=${SPECTACULAR_JWT_SHARED_SECRET:?SPECTACULAR_JWT_SHARED_SECRET needs to be set in a .env file with a 32byte text secret}
        volumes:
            - ${SPECTACULAR_GITHUB_APP_PRIVATE_KEY_FILE_PATH:?SPECTACULAR_GITHUB_APP_PRIVATE_KEY_FILE_PATH needs to be set in a .env file with the location of a .pem private key provided for the GitHub app}:/usr/spectacular/github.private-key.pem:ro
    auth:
        image: tarent/loginsrv:1.3.0
        environment: 
            - LOGINSRV_GITHUB=client_id=${SPECTACULAR_GITHUB_CLIENT_ID:?SPECTACULAR_GITHUB_CLIENT_ID needs to be set in a .env file with a GitHub app client id},client_secret=${SPECTACULAR_GITHUB_CLIENT_SECRET:?SPECTACULAR_GITHUB_CLIENT_SECRET needs to be set in a .env file with a GitHub app client secret}
            - LOGINSRV_JWT_SECRET=${SPECTACULAR_JWT_SHARED_SECRET:?SPECTACULAR_JWT_SHARED_SECRET needs to be set in a .env file with a 32byte text secret}
            - LOGINSRV_COOKIE_SECURE="false"
