version: '3'
services:
    web:
        build: 
            context: .
            dockerfile: ./docker/Dockerfile-web
    backend:
        build: 
            context: .
            dockerfile: ./docker/Dockerfile-backend
