version: '3'
services:
    web:
        image: spectacular-web
        build: 
            context: .
            dockerfile: ./docker/Dockerfile-web
        environment:
            - API_LOCATION=http://backend
            - AUTH_LOCATION=http://auth:8080
    backend:
        image: spectacular-backend
        build: 
            context: .
            dockerfile: ./docker/Dockerfile-backend
        ports:
            - "5000:80"
    auth:
        ports:
            - "5001:8080"
