version: '3'
services:
    web:
        image: spectacular-web
        build: 
            context: .
            dockerfile: ./docker/Dockerfile-web
    backend:
        image: spectacular-backend
        build: 
            context: .
            dockerfile: ./docker/Dockerfile-backend
