FROM node:16.17 AS build

# Set the node env max memory limit
ENV NODE_OPTIONS --max-old-space-size=2048

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY web/package*.json ./
RUN npm install

# Copy build config files
COPY web/babel.config.js web/webpack.config.js web/tsconfig.json web/.eslintrc.yml web/jest.config.json ./

# Copy api spec file
COPY backend/specs/backend-api.yaml ../backend/specs/

# Copy app source, theme & test mocks
COPY web/src src
COPY web/my-custom-semantic-theme my-custom-semantic-theme
COPY web/__mocks__ __mocks__

# Generate code
RUN npm run generate-fetcher

# Test
RUN npm run lint
RUN npm run test-ci

# Set version
ARG SEMVER
ARG SHORTSHA
ENV SEMVER ${SEMVER:-local}
ENV SHORTSHA ${SHORTSHA:-local}
RUN echo $SEMVER
RUN echo $SHORTSHA

# Bundle
RUN npm run build

###
FROM nginx:1.16.1

ENV API_LOCATION=http://backend

# Copy bundled web files
COPY --from=build /usr/src/app/dist /usr/share/nginx/html

# Copy and web config template
COPY web/web.template.conf /etc/nginx/conf.d/web.template

CMD ["bash", "-c", "envsubst '$${API_LOCATION}' < /etc/nginx/conf.d/web.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"]
