apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: spectacular-auth
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spectacular-auth 
    spec:
      containers:
        - name: spectacular-auth
          image: tarent/loginsrv:1.3.0
          ports:
          - containerPort: 8080
          env:
          - name: LOGINSRV_COOKIE_SECURE
            value: "false"
          - name: LOGINSRV_GITHUB
            valueFrom:
              secretKeyRef:
                name: github-oauth
                key: oauth-config
          - name: LOGINSRV_JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: auth-keys
                key: shared-signing-key
          resources:
            requests:
              cpu: 100m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 64Mi
