@startuml domain-model

title Spectuacular Domain Model

class "Repository" {
  owner : String
  name : String
  htmlUrl : String
}

class "Catalogue" {
  id : String
  repository : Repository
  catalogueManifest : CatalogueManifest
  specLogs : List<SpecLog>
  error : String
  with(List<SpecLog>) : Catalogue
}

class "SpecFileLocation" {
  repo : Repository
  filePath : String
}

class "CatalogueManifest" {
  name : String
  description : String
  specFileLocations : List<SpecFileLocation>
}

class "SpecLog" {
  id : String
  latestAgreed : SpecItem
  proposedChanges : List<ProposedSpecChange>
}

class "SpecItem" {
  id : String
  repository : Repository
  filePath : String
  htmlUrl : String
  ref : String
  sha : String
  lastModified : Instant
  parseResult : OpenApiSpecParseResult
}

class "ProposedSpecChange" {
  id : int
  pullRequest : PullRequest
  specItem : SpecItem
}

class "OpenApiSpec" {
  title : String
  version : String
  operations : List<OpenApiOperation>
}

class "OpenApiOperation" {
  path : String
  name : String
  topicName : String
}

class "OpenApiSpecParseResult" {
  openApiSpec : OpenApiSpec
  errors : List<String>
  hasErrors() : boolean
}

class "PullRequest" {
  repository : Repository
  branchName : String
  number : int
  url : String
  labels : List<String>
  changedFiles : List<String>
  title : String
  updatedAt : Instant
  changesFile(Repository, String) : boolean
}

"Catalogue" --> "Repository" : repository
"Catalogue" --> "CatalogueManifest" : catalogueManifest
"Catalogue" --> "*" "SpecLog" : specLogs
"SpecFileLocation" --> "Repository" : repo
"CatalogueManifest" --> "*" "SpecFileLocation" : specFileLocations
"SpecLog" --> "SpecItem" : latestAgreed
"SpecLog" --> "*" "ProposedSpecChange" : proposedChanges
"SpecItem" --> "Repository" : repository
"SpecItem" --> "OpenApiSpecParseResult" : parseResult
"ProposedSpecChange" --> "PullRequest" : pullRequest
"ProposedSpecChange" --> "SpecItem" : specItem
"OpenApiSpec" --> "*" "OpenApiOperation" : operations
"OpenApiSpecParseResult" --> "OpenApiSpec" : openApiSpec
"PullRequest" --> "Repository" : repository

@enduml
