apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: spectacular-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spectacular-frontend 
    spec:
      containers:
        - name: spectacular-frontend 
          image: spectacular.azurecr.io/spectacular-frontend
          ports:
          - containerPort: 80
