apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: spectacular-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spectacular-web 
    spec:
      containers:
        - name: spectacular-web 
          image: spectacular.azurecr.io/spectacular-web
          ports:
          - containerPort: 80
          env:
          - name: API_LOCATION
            value: "http://spectacular-backend"
