apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: spectacular-backend 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spectacular-backend 
    spec:
      containers:
        - name: spectacular-backend 
          image: spectacular.azurecr.io/spectacular-backend
          ports:
          - containerPort: 80
          env:
          - name: GITHUB_APP_PRIVATE_KEY_FILE_PATH
            value: "/usr/spectacular/private-key.pem"
          - name: GITHUB_APP_ID
            valueFrom:
              secretKeyRef:
                name: github-app
                key: app-id
          - name: JWT_SHARED_SECRET
            valueFrom:
              secretKeyRef:
                name: auth-keys
                key: shared-signing-key
          volumeMounts:
          - name: private-key-volume
            mountPath: "/usr/spectacular/"
            readOnly: true
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1024Mi
      volumes:
      - name: private-key-volume
        secret:
          secretName: github-app
          items:
          - key: private-key.pem
            path: private-key.pem
