env:
  browser: true
  es6: true
  jest/globals: true
extends:
  - 'plugin:react/recommended'
  - airbnb-typescript
  - 'plugin:@typescript-eslint/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  VERSION: readonly
  SHORTSHA: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
  project: ./tsconfig.json
plugins:
  - react
  - jest
  - '@typescript-eslint'
rules: 
  linebreak-style: 0
  react/prop-types: 0
  react/require-default-props: 0
  react/jsx-filename-extension: 0
  max-len: 
    - 2
    - code: 140
  "@typescript-eslint/camelcase": off
ignorePatterns:
 - backend-api-client.tsx
