env:
  browser: true
  es6: true
  jest/globals: true
extends:
  - 'plugin:react/recommended'
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  VERSION: readonly
  SHORTSHA: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - jest
rules: 
  linebreak-style: 0
  react/prop-types: 0
  react/jsx-filename-extension: 0
  max-len: 
    - 2
    - code: 140
